classDiagram
%% ================== Pessoas ==================
class Usuario {
  <<abstract>>
  +UUID id
  +String nome
  +String email
}

class Vendedor {
  +String matricula
}
Usuario <|-- Vendedor

class Supervisor {
  +Decimal limiteAprovacao
}
Usuario <|-- Supervisor

class Cliente {
  +String cpf
  +String nomeCompleto
  +String telefone
  +Date dataNascimento
}
Cliente "1" o-- "1..*" Endereco : possui

class Endereco {
  +String logradouro
  +String numero
  +String complemento
  +String bairro
  +String cidade
  +String uf
  +String cep
}

%% ================== Empresa ==================
class Empresa {
  +String cnpj
  +String razaoSocial
  +String nomeFantasia
}
Empresa "1" *-- "1" Endereco : endereço
Empresa "1" --> "0..*" Vendedor
Empresa "1" --> "0..*" Supervisor
Empresa "1" --> "0..*" Cliente

%% ================== Catálogo de Produtos ==================
class Categoria {
  +UUID id
  +String nome
}
class Subcategoria {
  +UUID id
  +String nome
}
class Fabricante {
  +String cnpj
  +String nome
}
class Produto {
  +UUID id
  +String sku
  +String nome
  +String descricao
  +Decimal valorUnitario
  +Integer quantidadeEstoque
}
Subcategoria --> Categoria
Produto --> Subcategoria
Produto --> Fabricante
Empresa --> Produto : catálogo

%% ================== Vendas ==================
class Pedido {
  +UUID id
  +Date data
  +Decimal totalBruto
  +Decimal desconto
  +Decimal totalLiquido
  +PedidoStatus status
}
class ItemPedido {
  +Integer quantidade
  +Decimal valorUnitario
  +Decimal subtotal
}
Pedido "1" *-- "1..*" ItemPedido
Pedido --> Cliente
Pedido --> Vendedor : registradoPor
Pedido --> Empresa

%% ================== Pagamentos ==================
class FormaPagamento {
  +UUID id
  +String descricao
}
class Pagamento {
  +UUID id
  +Decimal valor
  +Date data
  +PagamentoStatus status
  +String nsu
}
Pedido --> Pagamento
Pagamento --> FormaPagamento

%% ================== Aprovação ==================
class AprovacaoPedido {
  +UUID id
  +Date data
  +String observacao
  +AprovacaoStatus status
}
Pedido o-- AprovacaoPedido : histórico
AprovacaoPedido --> Supervisor

%% ================== Enums ==================
class PedidoStatus {
  <<enumeration>>
  ABERTO
  EM_APROVACAO
  APROVADO
  REPROVADO
  FINALIZADO
  CANCELADO
}
class PagamentoStatus {
  <<enumeration>>
  PENDENTE
  AUTORIZADO
  NEGADO
  LIQUIDADO
}
class AprovacaoStatus {
  <<enumeration>>
  PENDENTE
  APROVADO
  REPROVADO
}
